import type { Cookies } from '@sveltejs/kit';
const enc = new TextEncoder();
function b64(data: ArrayBuffer | string) { const bytes = typeof data === 'string' ? enc.encode(data) : new Uint8Array(data); return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,''); }
function unb64(s: string) { const raw = atob(s.replaceAll('-','+').replaceAll('_','/') + '='.repeat((4-s.length%4)%4)); return Uint8Array.from(raw, c => c.charCodeAt(0)); }
export async function hashPassword(password: string, salt: string = String(crypto.randomUUID())) { const key = await crypto.subtle.importKey('raw', enc.encode(password), 'PBKDF2', false, ['deriveBits']); const bits = await crypto.subtle.deriveBits({name:'PBKDF2', salt:enc.encode(salt), iterations:310000, hash:'SHA-256'}, key, 256); return `${salt}.${b64(bits)}`; }
export async function verifyPassword(password: string, stored: string) { const [salt, expected] = stored.split('.'); if (!salt || !expected) return false; const actual = (await hashPassword(password, salt)).split('.')[1]; return actual === expected; }
export async function signJwt(payload: Record<string, unknown>, secret: string) { const h=b64(JSON.stringify({alg:'HS256',typ:'JWT'})); const p=b64(JSON.stringify({...payload,iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+60*60*24*28})); const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']); const sig=await crypto.subtle.sign('HMAC',key,enc.encode(`${h}.${p}`)); return `${h}.${p}.${b64(sig)}`; }
export async function readJwt(cookies: Cookies, secret: string) { const token=cookies.get('fantasy_session'); if (!token) return null; const [h,p,s]=token.split('.'); if (!h||!p||!s) return null; const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']); const valid=await crypto.subtle.verify('HMAC',key,unb64(s),enc.encode(`${h}.${p}`)); if (!valid) return null; const body=JSON.parse(new TextDecoder().decode(unb64(p))); return body.exp>Date.now()/1000?body:null; }
export function setSession(cookies: Cookies, token: string) { cookies.set('fantasy_session',token,{path:'/',httpOnly:true,secure:true,sameSite:'lax',maxAge:60*60*24*28}); }
